[package]
name = "sundowns-portfolio"
description = "Yew web app portfolio for Tom Smallridge (Sundowns)"
version = "0.1.0"
authors = ["Tom Smallridge <tom.smallridge@versent.com.au>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"
